### ISSUE TITLE
Kernel boots only 3 dots - maybe a loader problem?

### ISSUE THREAD

**Issue by doclulle** [XboxDev/xbox-linux#1]
Hi,
I tried to give xbox-linux a reboot, so I compiled a kernel and initrd for the xbox and started it with GentooX Loader. 
It loads the kernel, prints loading and 3 dots and that's it. 

Clearly, I am missing something, but i can't figure it out. So let me explain what I did:
-Installed a VM: debian bullseye 32bit
-Pulled the xbox-sources and compiled a kernel for that VM. So basically I downgraded from 5.10 to 5.8.1.
-Installed kernel, rebootet and a got a debian system running the 5.8.1 kernel.
-copied the xbox-config to .config and compiled again:
  make, ........., and finally a make install. That generates also the initrd and copies everything to /boot:

`-rw-r--r-- 1 root root  86K 28. Feb 04:46 config-5.8.1-xboxdev-gcc89bd62acde

-rw-r--r-- 1 root root  12M 28. Feb 04:46 initrd.img-5.8.1-xboxdev-gcc89bd62acde

-rw-r--r-- 1 root root 2,0M 28. Feb 04:46 System.map-5.8.1-xboxdev-gcc89bd62acde

-rw-r--r-- 1 root root 3,4M 28. Feb 04:46 vmlinuz-5.8.1-xboxdev-gcc89bd62acde`

So far so good. Now to the XBOX:
-Installed Gentoox Home on E:
-Replaced the Gentoox kernel and initrd with the 5.8.1 xboxdev versions.
Started the Gentoox Loader: It says something like: loading kernel with the correct file name and after 3 dots it hangs...
So maybe I need to tweak the append line in the loader config? In desperation I also tried the gentoox initrd and the xboxdev kernel. No surprise, aöso doenst work.

Any Ideas?

I know it's kinda lazy way, but I think if my dev system is very close to the target system this can't be a bad idea and everything should work fine?

I would be so glad to hear from you!

lu

**Comment by dust08** [comment]
Looks like it's because your initrd is too large? For some reason going over approx. 7mb for the initramfs/initrd causes it to lock exactly as you are indicating. Use dracut to create an initramfs with the minimal config needed to mount your rootfs that should give you one small enough. Could also make your own from busybox w/ a custom init script, or just use the alpine minirootfs w/ a custom init. Could also be something with you kernel config/modules might want to just try building all modules into the kernel.

Could just steal my kernel and initramfs from here: https://drive.google.com/file/d/14C07TJ1an-kwCVvnBnN5vcLLIeKckfSj/view?usp=sharing would need to extract the initramfs, edit the init script and rebuild though. Might work fine if you compress your debian rootfs and replace the alpine one but you would lose all changes when you shut it down unless you do custom start up and shut down scripts to get persistance.

**Comment by haxar** [comment]
Hi there,

Since the title of this issue refers to a loader problem & not the Linux kernel, I will be closing this.

Anything GentooX related is legacy code & not maintained by the XboxDev org.  You would have better luck with Cromwell.
