### ISSUE TITLE
Mainlining

### ISSUE THREAD

**Issue by upintheairsheep** [XboxDev/xbox-linux#3]
Hello, can you please mainline into the master Linux kernel, unless core code of the Linux kernel has been modified apart from Kconfig?

**Comment by haxar** [comment]
> core code of the Linux kernel has been modified

This is true because the original Xbox utilizes a unified memory architecture (UMA) & does not utilize system memory, which in turn modifies the Linux PCI detection logic to not touch where the system memory PCI devices would be on a typical motherboard, as it's a known quirk to hang in that area.

This repo is board specific with lots of historical hacks to get Linux to run.  Not possible to upstream.

**Comment by upintheairsheep** [comment]
> > core code of the Linux kernel has been modified
> 
> This is true because the original Xbox utilizes a unified memory architecture (UMA) & does not utilize system memory, which in turn modifies the Linux PCI detection logic to not touch where the system memory PCI devices would be on a typical motherboard, as it's a known quirk to hang in that area.
> 
> This repo is board specific with lots of historical hacks to get Linux to run. Not possible to upstream.

Well the only thing we can really mainline is Microdia/Hip Gear Xbox Communicator support, for those communicators connected to Xbox-to-USB adapters.
